-- Table: nfe

-- DROP TABLE nfe;

CREATE TABLE nfe
(
  infnfe_statusnfe character(30),
  infnfe_versao character(4),
  infnfe_id character(47),
  infnfe_pedidovenda numeric(6,0),
  infnfe_danfeimpresso character(3),
  infnfe_xmlexportado character(3),
  
  ide_cuf numeric(2,0),  
  ide_xuf character(2),
  ide_cnf numeric(8,0),
  ide_natop character(60),
  ide_indpag numeric(1,0),
  ide_mod numeric(2,0),
  ide_serie numeric(3,0),
  ide_nnf numeric(9,0),
  ide_dhemi timestamp without time zone,
  ide_dhsaient timestamp without time zone,
  ide_tpnf numeric(1,0),
  ide_iddest numeric(1,0),
  ide_cmunfg numeric(7,0),
  ide_xmunfg character(60),
  ide_tpimp numeric(1,0),
  ide_tpemis numeric(1,0),
  ide_cdv numeric(1,0),
  ide_tpamb numeric(1,0),
  ide_finnfe numeric(1,0),
  ide_indfinal numeric(1,0),
  ide_indpres numeric(1,0),
  ide_procemi numeric(1,0),
  ide_verproc character(20),
  ide_dhcont timestamp without time zone,
  ide_xjust character(256),
  
  emit_cnpj character(14),
  emit_cpf character(11),
  emit_xnome character(60),
  emit_xfant character(60),
  
  enderemit_xlgr character(60),
  enderemit_nro character(60),
  enderemit_xcpl character(60),
  enderemit_xbairro character(60),
  enderemit_cmun numeric(7,0),
  enderemit_xmun character(60),
  enderemit_uf character(2),
  enderemit_cep numeric(8,0),
  enderemit_cpais numeric(4,0),
  enderemit_xpais character(60),
  enderemit_fone numeric(14,0),
  enderemit_ie numeric(14,0),
  enderemit_iest numeric(14,0),
  enderemit_im character(15),
  enderemit_cnae character(7),
  enderemit_crt numeric(1,0),
  
  dest_cnpj character(14),
  dest_cpf character(11),
  dest_idestrangeiro character(20),
  dest_xnome character(60),
  
  enderdest_xlgr character(60),
  enderdest_nro character(60),
  enderdest_xcpl character(60),
  enderdest_xbairro character(60),
  enderdest_cmun numeric(7,0),
  enderdest_xmun character(60),
  enderdest_uf character(2),
  enderdest_cep numeric(8,0),
  enderdest_cpais numeric(4,0),
  enderdest_xpais character(60),
  enderdest_fone numeric(14,0),
  enderdest_indiedest numeric(1,0),
  enderdest_ie numeric(14,0),
  enderdest_isuf numeric(9,0),
  enderdest_im character(15),
  enderdest_email character(60),
  
  retirada_cnpj character(14),
  retirada_cpf character(11),
  retirada_xlgr character(60),
  retirada_nro character(60),
  retirada_xcpl character(60),
  retirada_xbairro character(60),
  retirada_cmun numeric(7,0),
  retirada_xmun character(60),
  retirada_uf character(2),
  
  entrega_cnpj character(14),
  entrega_cpf character(11),
  entrega_xlgr character(60),
  entrega_nro character(60),
  entrega_xcpl character(60),
  entrega_xbairro character(60),
  entrega_cmun numeric(7,0),
  entrega_xmun character(60),
  entrega_uf character(2),

  retenvinfe_versao numeric(5,2),
  retenvinfe_cstat numeric(3,0),
  retenvinfe_dhrecbto timestamp without time zone,
  retenvinfe_tpamb numeric(1,0),
  retenvinfe_veraplic character(20),
  retenvinfe_xmsg character(255),
  retenvinfe_cuf numeric(2,0),
  retenvinfe_tmed numeric(6,4),
  retenvinfe_nrec numeric(15,0),

  retconsrecinfe_versao numeric(5,2),
  retconsrecinfe_cstat numeric(3,0),
  retconsrecinfe_nrec numeric(15,0),
  retconsrecinfe_dhrecbto timestamp without time zone,
  retconsrecinfe_tpamb numeric(1,0),
  retconsrecinfe_veraplic character(20),
  retconsrecinfe_xmsg character(200),
  retconsrecinfe_cmsg numeric(4,0),
  retconsrecinfe_xmotivo character(255),  
  retconsrecinfe_cuf numeric(2,0),

  retconsrecinfe_protnfe_chnfe numeric(44,0),
  retconsrecinfe_protnfe_versao numeric(5,2),
  retconsrecinfe_protnfe_tpamb numeric(1,0),
  retconsrecinfe_protnfe_veraplic character(20),
  retconsrecinfe_protnfe_cstat numeric(3,0),
  retconsrecinfe_protnfe_xmotivo character(255),
  retconsrecinfe_protnfe_dhrecbto timestamp without time zone,
  retconsrecinfe_protnfe_xmsg character(200),
  
  protnfe_versao numeric(5,2),
  infprot_tpamb numeric(1,0),
  infprot_veraplic character(20),
  infprot_chnfe numeric(44,0),
  infprot_dhrecbto timestamp without time zone,
  infprot_nprot numeric(15,0),
  infprot_digval character(200),
  infprot_cstat numeric(3,0),
  infprot_xmotivo character(255),

  icmstot_vbc numeric(15,2),
  icmstot_vicms numeric(15,2),  
  icmstot_vicmsdeson numeric(15,2), 
  icmstot_vbcst numeric(15,2),
  icmstot_vst numeric(15,2),
  icmstot_vprod numeric(15,2),
  icmstot_vfrete numeric(15,2),  
  icmstot_vseg numeric(15,2),
  icmstot_vdesc numeric(15,2),
  icmstot_vii numeric(15,2),
  icmstot_vipi numeric(15,2),
  icmstot_vpis numeric(15,2),
  icmstot_vcofins numeric(15,2),
  icmstot_voutro numeric(15,2),
  icmstot_vnf numeric(15,2),
  icmstot_vtottrib numeric(15,2),  

  transp_modfrete numeric(1,0),
  
  transporta_cnpj character(14),
  transporta_cpf character(11),
  transporta_xnome character(60),
  transporta_ie numeric(14,0),  
  transporta_xender character(60),
  transporta_xmun character(60),  
  transporta_uf character(2),

  vol_qvol numeric(15,0),  
  vol_esp character(60), 
  vol_marca character(60),
  vol_nvol character(60),
  vol_pesol numeric(15,2),  
  vol_pesob numeric(15,2),

  fat_nfat character(60), 
  fat_vorig numeric(15,2),
  fat_vdesc numeric(15,2),
  fat_vliq numeric(15,2),

  infadic_infadfisco text,  
  infadic_infcpl text,
  
  signature_cnpj character(14),
  signature_emissor character(200),
  signature_assunto character(200),
  signature_datainicial timestamp without time zone,
  signature_datafinal timestamp without time zone,

  retenvevento_versao numeric(5,2),
  retenvevento_idlote numeric(15,0),
  retenvevento_tpamb numeric(1,0),
  retenvevento_veraplic character(20),
  retenvevento_corgao numeric(2,0),
  retenvevento_cstat numeric(3,0),
  retenvevento_xmotivo character(255),

  retenvevento_retevento_versao numeric(5,2),
  retenvevento_retevento_infevento_id character(17),
  retenvevento_retevento_infevento_tpamb numeric(1,0),
  retenvevento_retevento_infevento_veraplic character(20),
  retenvevento_retevento_infevento_corgao numeric(2,0),
  retenvevento_retevento_infevento_cstat numeric(3,0),
  retenvevento_retevento_infevento_xmotivo character(255),
  retenvevento_retevento_infevento_chnfe numeric(44,0),
  retenvevento_retevento_infevento_tpevento numeric(6,0),
  retenvevento_retevento_infevento_xevento character(60),
  retenvevento_retevento_infevento_nseqevento numeric(2,0),
  retenvevento_retevento_infevento_cnpjdest character(14),
  retenvevento_retevento_infevento_cpfdest character(11),
  retenvevento_retevento_infevento_emaildest character(60),
  retenvevento_retevento_infevento_dhregevento timestamp without time zone,
  retenvevento_retevento_infevento_nprot numeric(15,0),
  
  xml_assinado xml,
  xml_autorizado xml,
  
  xml_envevento_assinado xml,
  xml_envevento_autorizado xml

  )
WITH (
  OIDS=TRUE
);
ALTER TABLE nfe
  OWNER TO osvaldo;